
project: teller

# Set this if you want to carry over parent process' environment variables
carry_env: true


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development


#
# Providers
#
providers:

#  dotenv:
##    env_sync:
##      path: ~/teller-env.env
#    env:
#      ANSIBLE_VAULT_PASSPHRASE:
#        path: ~/teller-env.env

  # Configure via environment variables for integration:
  # ANSIBLE_VAULT_PASSPHRASE: Ansible Vault Password

  ansible_vault:
    env_sync:
       path: ansible/vars/vault_{{stage}}.yml

    env:
      KEY1:
        path: ansible/vars/vault_{{stage}}.yml
      NONEXIST_KEY:
        path: ansible/vars/vault_{{stage}}.yml
