// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/onepassword.go

// Package mock_providers is a generated GoMock package.
package mock_providers

import (
	reflect "reflect"

	onepassword "github.com/1Password/connect-sdk-go/onepassword"
	gomock "github.com/golang/mock/gomock"
)

// MockOnePasswordClient is a mock of OnePasswordClient interface.
type MockOnePasswordClient struct {
	ctrl     *gomock.Controller
	recorder *MockOnePasswordClientMockRecorder
}

// MockOnePasswordClientMockRecorder is the mock recorder for MockOnePasswordClient.
type MockOnePasswordClientMockRecorder struct {
	mock *MockOnePasswordClient
}

// NewMockOnePasswordClient creates a new mock instance.
func NewMockOnePasswordClient(ctrl *gomock.Controller) *MockOnePasswordClient {
	mock := &MockOnePasswordClient{ctrl: ctrl}
	mock.recorder = &MockOnePasswordClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnePasswordClient) EXPECT() *MockOnePasswordClientMockRecorder {
	return m.recorder
}

// GetItemByTitle mocks base method.
func (m *MockOnePasswordClient) GetItemByTitle(title, vaultUUID string) (*onepassword.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByTitle", title, vaultUUID)
	ret0, _ := ret[0].(*onepassword.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByTitle indicates an expected call of GetItemByTitle.
func (mr *MockOnePasswordClientMockRecorder) GetItemByTitle(title, vaultUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByTitle", reflect.TypeOf((*MockOnePasswordClient)(nil).GetItemByTitle), title, vaultUUID)
}

// UpdateItem mocks base method.
func (m *MockOnePasswordClient) UpdateItem(item *onepassword.Item, vaultUUID string) (*onepassword.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", item, vaultUUID)
	ret0, _ := ret[0].(*onepassword.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockOnePasswordClientMockRecorder) UpdateItem(item, vaultUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockOnePasswordClient)(nil).UpdateItem), item, vaultUUID)
}
